import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignOutButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { shadcn } from "@clerk/themes";
import { auth } from "@clerk/nextjs/server";
import { Button } from "@/components/ui/button";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  return (
    <html
      lang="en"
      className="h-full antialiased dark"
      style={{ colorScheme: "dark" }}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider appearance={{ theme: shadcn }}>
          <header className="flex items-center justify-end gap-2 border-b px-4 py-3">
            {!userId && (
              <>
                <SignInButton mode="modal">
                  <Button variant="outline">Sign in</Button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <Button>Sign up</Button>
                </SignUpButton>
              </>
            )}
            {userId && (
              <>
                <SignOutButton>
                  <Button variant="outline">Sign out</Button>
                </SignOutButton>
                <UserButton />
              </>
            )}
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
